-- 코드를 작성해주세요
WITH RECURSIVE GENERATIONS AS (
    SELECT ID,PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID,E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    INNER JOIN GENERATIONS G ON E.PARENT_ID = G.ID
)

SELECT ID
    FROM GENERATIONS
    WHERE GENERATION = 3
    ORDER BY ID