-- 코드를 입력하세요
SELECT r.REST_ID, r.REST_NAME, r.FOOD_TYPE, r.FAVORITES, r.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE),2) as SCORE
FROM REST_REVIEW rr
LEFT JOIN REST_INFO r ON r.REST_ID = rr.REST_ID 
GROUP BY r.REST_ID
HAVING r.ADDRESS like "서울%"
ORDER BY SCORE DESC, r.FAVORITES DESC