-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
 COUNT(DISTINCT U.USER_ID) AS PURCHASED_ID, 
 ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT (*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PURCHASED_RATIO
    FROM ONLINE_SALE O
    LEFT JOIN USER_INFO U ON U.USER_ID = O.USER_ID
    WHERE U.JOINED LIKE '2021%'
    GROUP BY YEAR, MONTH
    ORDER BY YEAR, MONTH