WITH recursive generations as (
    SELECT ID, PARENT_ID, 1 AS GENERATION
        FROM ECOLI_DATA 
        WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
        FROM ECOLI_DATA e
        INNER JOIN generations g 
        ON e.PARENT_ID = g.ID
)

# SELECT ID, PARENT_ID, 1 AS GENERATION
#     FROM ECOLI_DATA 
#     WHERE PARENT_ID IS NULL
    
#     UNION ALL
    
#     SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
#     FROM ECOLI_DATA e
#     INNER JOIN generations g 
#     ON e.PARENT_ID = g.ID

SELECT  COUNT(*) AS COUNT, GENERATION
        FROM GENERATIONS
        WHERE ID NOT IN (SELECT PARENT_ID FROM GENERATIONS WHERE PARENT_ID IS NOT NULL)
        GROUP BY GENERATION
        ORDER BY GENERATION ASC