-- 코드를 작성해주세요
WITH FE AS(
    SELECT SUM(CODE) AS FE_SUM
        FROM SKILLCODES
    WHERE CATEGORY = "FRONT END"
    GROUP BY CATEGORY
),
RESULT AS(SELECT CASE
        WHEN SKILL_CODE & FE_SUM
                AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
        THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
        THEN 'B'
        WHEN SKILL_CODE & FE_SUM
        THEN 'C'
        ELSE NULL
        END GRADE,
        ID,
        EMAIL
        FROM DEVELOPERS, FE
)

SELECT *
    FROM RESULT
    WHERE GRADE IS NOT NULL
    ORDER BY GRADE, ID